## database configuration 
db.driver=oracle.jdbc.driver.OracleDriver
db.url=jdbc:oracle:thin:@localhost:1521:orcl
db.username=atmsystem
db.password=1234

# Connection Pool Configuration
db.pool.maxSize=10
db.pool.minIdle=5
db.pool.timeout=30000